# Generated by Django 5.1.7 on 2025-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_itemacervo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemacervo',
            name='datacao',
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='datacao_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemacervo',
            name='datacao_de',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemacervo',
            name='estado_conservacao',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('pessimo', 'Péssimo'), ('restaurado', 'Restaurado')], default='bom', max_length=20),
        ),
    ]
